opentomb/OpenTomb

src/camera.h, src/game.cpp, src/game.h
Improved camera rotation with early collision detection.
Cleaned up Cam_FollowEntity()@Game.cpp where possible.
=> Update Camera Rotation Code

CMakeLists.txt, resource/icon/opentomb.rc
=> Add icon to OpenTomb.exe in automated builds

src/audio.cpp, src/audio.h
=> use libsndfile for ogg loading

CMakeLists.txt
=> Optional FIND_PACKAGE for SDL, for systems without pkgconfig

cmake/FindSDL2.cmake, cmake/FindSDL2Image.cmake
Missing files for
Optional FIND_PACKAGE for SDL, for systems without pkgconfig #156
=> FindSDL2.cmake FindSDL2Image.cmake

doc/images/icons/README, doc/trosettastone-orig.htm, doc/trosettastone.asc, doc/trosettastone.html
asciidoc conversion of trosettastone for further improvability.
=> Trosettastone

src/camera.h, src/character_controller.h, src/console.cpp, src/engine.cpp, src/portal.cpp, src/resource.cpp, src/vmath.cpp
What should be fixed:
* rotation of objects
* Lara and other objects are rendered the way they should be
What is not fixed:
* transparency - some rooms are not visible when you look at them through a transparent object
* Lara is leaning to the right, sometimes to a point where her head is upside down
Contains also various other fixes that will hopefully not break any existing functionality.
=> Correct orientation of animations and rotation of objects + various other fixes

config.lua, src/engine.cpp, src/script.cpp, src/system.h
Adds a config option to enable/disable vsync.
(If this doesn't do anything for you, please check if you have it forced to on/off in your graphics driver settings)
=> added vsync screen-configuration option

src/game.cpp
This changes the camera up/down rotation to a more common behaviour - I'm not sure if I anyone would prefer the current, or if it's just wasting code making this an optional mode?
=> changed camera rotation behaviour: Up/down circles around target

src/inventory.cpp, src/main_SDL.cpp, src/vt/vt_level.cpp
=> Add missing headers that prevent project from being built.

.travis.yml, CMakeLists.txt, cmake/FindSDL2.cmake
Provides a basic Travis CI script, yet it doesn't build because of platform-specific (Linux) problems. See https://travis-ci.org/stohrendorf/EdisonEngine/builds/139702888 for a few of the problems.
=> Travis CI script and very basic CMakeLists.txt

TODO.md
I tried to tidy up the formatting/syntax in the TODO document. Hope you don't mind!
I'm also adding in a few by request, tell me if I should edit anything.
=> Tidied TODO formatting

CMakeLists.txt
May only be merged once this branch passes Travis.
=> Try to split in-source external libs

CMakeLists.txt
This commit should be in the previous PR, not a separate one.
=> [NOT_FOR_MERGING] Fix OpenAL

extern/al/Alc/backends/backend.c
only initialization code, no strdup usage;
=> fixed OpenAL sdl backend (initialization correction);

src/character_controller.cpp, src/entity.cpp, src/skeletal_model.c, src/skeletal_model.h
added functions SSBoneFrame_SetTrget(...), SSBoneFrame_SetTargetingAxisMod(...), SSBoneFrame_SetTargetingLimit(...);
added and used field "enabled" to ss_animation_s structure;
fixed wrong frame logic (disabled animations has no frames);
=> updated targeting system control:

.travis.yml, CMakeLists.txt, ENGINE.md, TODO.md, opentomb-code.cbp, opentomb-code.depend, src/controls.cpp, src/core/system.c, src/engine.cpp, src/engine.h, src/gui.cpp, src/image.cpp, src/image.h, src/main_SDL.cpp
implemented: png, pcx loading;
saving is not implemented;
screenshots are saving in tga format;
=> created internal wrapper module for image loading / saving;

scripts/entity/entity_functions.lua, scripts/entity/script_switch.lua, scripts/level/tr1/LEVEL6_autoexec.lua, scripts/level/tr2/HOUSE_autoexec.lua, scripts/level/tr3/SHORE_autoexec.lua, scripts/system/debug.lua, scripts/trigger/helper_functions.lua, scripts/trigger/trigger_functions.lua, src/anim_state_control.cpp, src/character_controller.cpp, src/character_controller.h, src/entity.cpp, src/entity.h, src/game.cpp, src/gui.cpp, src/script.cpp, src/skeletal_model.c, src/skeletal_model.h, src/trigger.cpp, src/world.cpp
Updated anim control functional (and script) interface: added multi animation support;
=> Anim control interface

src/anim_state_control.cpp, src/entity.cpp, src/skeletal_model.c
removed physics update from SetAnim functions;
fixed anim_move command interpolation;
=> Anim control refactoring

scripts/audio/soundtrack.lua, src/audio.cpp, src/script.cpp
first stable solution; need time to check it;
=> audio streams loading moved to level loading stage;

src/audio.cpp, src/skeletal_model.h
Fixed AL buffers manipulation;
Added WAD file tracks loading; 
TODO: fix ogg streaming;
=> Audio fixing

scripts/entity/entity_functions.lua, src/core/vmath.c, src/core/vmath.h, src/entity.cpp, src/entity.h, src/script.cpp
more correct activation offset testing;
activation angle offset is a parameter, not hardcode;
=> Activation offset

src/physics.h, src/physics_bullet.cpp, src/resource.cpp, src/resource.h, src/room.cpp, src/room.h, src/world.cpp, src/world.h
now in every success  rooms flipping altroom portal tweens are rebuild-ed;
no more hacky logic: correct in all cases;
=> added dynamic altroom portals tweens generation;

doc/flipeffects.asc, doc/floordata.asc, doc/mesh_construction_animation.asc, doc/room_geometry.asc, doc/sound.asc, doc/trosettastone.asc, doc/trosettastone.html
I did my best to describe whole flipeffect concept, as well as each flipeffect for every game version. Only two unknowns are two mysterious flipeffects 31 and 33 in TR5. I hope someone will do some research on this.
=> TRS3 - complete flipeffect guide

doc/floordata.asc, doc/trosettastone.html
Info verified with TR1-TR2 disassembly.
=> Critical update: TR1-2 fixed cameras info

src/anim_state_control.cpp, src/character_controller.cpp, src/entity.cpp, src/entity.h, src/game.cpp, src/physics_bullet.cpp, src/script/script_entity.cpp
- added auto position correction for Entity_SetAnimation function: for hardcoded anim state controlling without hardcoded magic offsets;
- fixed Entity_GetPenetrationFixVector algorithm;
- enabled anti-tunneling feature for Entity_GetPenetrationFixVector;
=> Set anim control and collision fixing

opentomb-code.cbp, src/audio.cpp, src/config-default/config-opentomb.h
Also remove super-old integrated AL sources from project and fix config path
NOTE: I didn't fix OpenAL paths, cause seems it works as is for everyone except me
=> Update codeblocks project to support OpenAL soft extensions again

scripts/autoexec.lua, scripts/character/character.lua, scripts/entity/entity_functions_common.lua, scripts/entity/entity_functions_enemies.lua, scripts/entity/entity_functions_switch.lua, scripts/entity/entity_model_ID_override.lua, scripts/entity/entity_properties.lua, src/character_controller.cpp, src/character_controller.h, src/entity.cpp, src/entity.h, src/gameflow.cpp, src/gameflow.h, src/mesh.c, src/mesh.h, src/physics/physics_bullet.cpp, src/render/render.cpp, src/render/render.h, src/resource.cpp, src/resource.h, src/script/script_character.cpp, src/script/script_entity.cpp, src/script/script_skeletal_model.cpp, src/skeletal_model.c, src/skeletal_model.h, src/state_control/state_control.cpp, src/state_control/state_control_Lara.cpp, src/state_control/state_control_gorilla.cpp, src/trigger.cpp, src/world.cpp
no hardcoded Lara setup in world.cpp
=> No hardcoded lara

README.md
=> Also requires libopenal-dev on most systems

src/game.cpp, src/render/shader_description.cpp, src/script/script.cpp, src/world.cpp
- key type fix for items_tree.
=> - avoiding possible overflows.

README.md, src/engine.cpp
As someone new to the project, and hoping to eventually contribute to the codebase, I thought I'd start slightly cleaning up the readme and adding a couple of (what I think are) important steps, for which I had to do a bit of digging to find answers.
I also added a line to the console help command to document the setgamef function.
I believe this will allow people new to the project to have an easier time getting up and running with the engine.
=> Slightly expand and clarify Readme/console help

README.md
=> fix @richardba username and link

README.md
=> Add links to openraider and icculus

ENGINE.md
- switch indentation to spaces and fixed indentation on sub-points
- names of directories and code portions are now inside small code blocks
- added link to Cochrane Github's page
- other minor improvements
/cc @Gh0stBlade @TeslaRus
=> Improvements on ENGINE.md

ENGINE.md
"build in" to "built-in"
/CC @Gh0stBlade @TeslaRus
=> Fix typo on ENGINE.md

scripts/strings/portuguese-ptbr/generic.lua, scripts/strings/portuguese-ptbr/global_items.lua, scripts/strings/portuguese-ptbr/sys_notify.lua
Please, do similar actions as #495 and #414. Feel free to change the directory name "portuguese-ptbr".
=> Add translation for Portuguese Brazil

Languages/es/README.md
Origin file [link](https://github.com/opentomb/OpenTomb/blob/master/README.md)
Please let me know if I created the right branch, correct me if I was mistaken.
=> Spanish translation of README.md file

languages/tl/readme.md
=> Filipino translation of README.md

Languages/ptpt/README.md
Origin file [link](https://github.com/opentomb/OpenTomb/blob/master/README.md)
Hello @TeslaRus, I translated this file into Portuguese from Portugal, and if you are interested I can also do it in Portuguese from Brazil.
I also created a new folder for Portuguese translations, to make it easier for contributors.
Please let me know if what I've done is alright. Greetings!
=> Portuguese ptpt translation of README.md file

config.lua, src/engine.cpp, src/render/render.h, src/script/script_config.cpp
Implementation of show_fps functionality, resolves issue #556
=> Implementation of show_fps functionality

src/engine.cpp, src/engine.h
Like it is mentioned in an issue #561 it's quite hard to get anything about an issue with SDL errors. I've added a bit more info in Sys_Error calls in the Engine.
=> A bit more verbose SDL errors

src/core/console.c, src/engine.cpp, src/gui/gui_inventory.cpp, src/skeletal_model.c, src/state_control/state_control_Lara.cpp
=> Fixed clang build warnings.

src/audio/audio_stream.cpp, src/engine.cpp, src/fmv/containers/rpl.c, src/gui/gui_menu.cpp, src/script/script_world.cpp
Following videos were crashing the game when trying to play them (it was due to unsupported audio format) :
* data/tr1/fmv/CAFE.RPL
* data/tr1/fmv/CANYON.RPL
* data/tr1/fmv/LIFT.RPL
* data/tr1/fmv/PRISON.RPL
Also, FMVs did not started from the beginning.
I'm trying to solve the bug that hangs the game when playing more than one FMV in the row, but you can merge this pull request if it is OK for you.
=> FMV fixes.
