opentomb/OpenTomb

- src/bordered_texture_atlas.cpp
- src/bordered_texture_atlas.h
- src/resource.cpp
- src/world.cpp
- src/world.h
There were a few architectural decisions about the bordered texture atlas that never sat very well with me, so now I finally took the time to change them.
- The atlas is now a proper C++ class, with constructor, destructor, everything. Cleaner design, makes a lot of code easier to read.
- A lot of details were changed to be in line with C++ standards, such as using bool and references.
- The atlas now takes all its values, meaning the texture pages and individual textures, at startup time and directly lays them out. This should be a bit faster as all memory is only allocated once. It's also a design that is overall more clearer: All work happens on creation; after that everything is read-only. Previously the atlas switched to the read-only mode the first time the result was requested, …
> Improvements to Bordered Texture Atlas

- src/entity.cpp
- src/resource.cpp
This fixes a bug where walls were only climbable in the room that marked them as climbable. The default approach for TR is that a wall is climbable if it is climbable in the room at the bottom of the stack. This was notable e.g. in the TR 2 mansion (the climbable wall leading out of the water), or in TR 2 Venice (BOAT.TR2), in the wooden hut (it was not possible to climb on from the second level) or the weird every-wall-is-climbable place.
(The revision history for this one is a bit longer than expected because I've first tried a different way of fixing the issue, which turned out to work only about 50% of the time. This new version works all the time.)
> Wall climbing fix

- doc/trosettastone.asc
Included SCRIPT.DAT/ENGLISH.DAT specification as used in TR4 and official TRLE. As far as I know, TR5 uses very similar chunk IDs, with the only difference being the weather command and possibly some command that has to do with Lara losing her weapons in one of the Russian levels. Need to find this out.
> Updated the documentation with SCRIPT.DAT specification

- src/entity.cpp
- src/entity.h
- src/game.cpp
- src/gui.cpp
- src/polygon.cpp
- src/vmath.cpp
Fixes:
- Lara's rolling animation (tested in TR1)
- Lara's position in noclip mode
- animations of entities (bats, doors, levers, ...)
- inventory and item notifier
- position of the zip-line handle (tested in TR2)
All patches are fairly simple and were made just by comparing the code before the C++ merge and after it.
> Rendering fixes

- src/entity.cpp
- src/mesh.cpp
- src/vmath.cpp
- src/vmath.h
Bullet's builtin quaternion slerp may produce result quaternions full of NaNs when the interpolated quats are very similar or identical.
This happens very frequently in an optimized build of the engine (gcc 4.9.2 with -O3), where Lara's limbs flicker randomly, causing mid-walk stumbles and on some maps (karnak.tr4) produce and "overflow in AABB" a couple of seconds after map start.
With the patch, an optimized build seems to work fine so far...
> replaced bullet's unstable quaternion slerp

- config.lua
- src/controls.cpp
- src/controls.h
- src/engine.cpp
- src/script.cpp
Removed some unneeded mouse-event handling: SDL_SetRelativeMouseMode already does the pointer hiding/warping and warp-reset filtering by itself, no need to do that in the event handling.
I also added configuration options for the axis scaling (this also allows to easily invert Y-axis via config with a negative scale...) - because it affects the same code part no separate pullreq for that :blush:
> SDL mousemode cleanup, added separate mouse axis scaling

- src/gui.cpp
Found by CDT's code analysis, fixes flashStart() without flashSetup() wrongly doing a fade-to-black.
> added missing break in fader init

- src/loader/datatypes.h
Top/bottom was flipped, resulting in chunks of gargabe textures in the atlas.
Since Tr4 (and likely Tr5) there is no centering alignment for use as billboard-item anymore (no room sprites), so the l/r/t/b calculation is just a dummy to fill these fields (IIRC, the tx/ty/tw/th match the sprite position/size from the original wad - they're probably a leftover from the level conversion).
> fixed sprite loading for tr4/5

- ENGINE.md
This updates the formatting of ENGINE.md to match the Markdown rules (see <http://daringfireball.net/projects/markdown/syntax>). Nothing big, it just makes the web version a bit nicer to look at.
(I'm mainly just trying out this pull request thing, which I have not used before. Looks nice.)
> Improve formatting of ENGINE.md

- CMakeLists.txt
- src/CMakeLists.txt
Setting the build type will generate the appropriate optimize-flags for compilation.
I also changed the build directory for the executable (was in src/, is now in the base dir, where it can be directly run)
> cmake: added build type selection, build exe in base dir

- CMakeLists.txt
There were three actual reasons:
- compiler warnings
- `std=c99` flag prevented linking of libvorbis
- no SDL2_image
> Make Travis happy

- src/anim_state_control.cpp
- src/character_controller.cpp
found that "middle hands pos" may contains too low z coordinate in some
animations; the solution is not full: 
- not all cases tested; 
- Lara can climb on through a wall;
- Character_GetMiddleHandsPos have to return point with z_max, not with z_middle;
> fixed sharp edges climbability checking;

- src/engine.cpp
These code pieces tried to do two different things, neither of which makes any sense:
-   Set up the current working directory to some external location to find files there
more easily. This uses a function that is not actually in the repository, and can thus
never work.
-   Avoid using SDL_image, because there were special code paths for OS X to use CoreImage
for saving. This code path is gone (and I think they should stay gone), so this lack of
initialization is definitely wrong.
This means mostly that the OS X version now uses the same source codes as all other
versions, which makes an awful lot of sense. However, it does not mean the Mac version works
yet.
There are no effects on other platforms.
> Remove Mac OS-specific #ifdefs

- CMakeLists.txt
- cmake/FindSDL2_image.cmake
PkgConfig seems to sort of find SDL2_image, but not the correct path to the library on
Mac OS. The custom find module solves this issue. It also has the side-effect of
removing the reliance on pkg-config as an external tool. That may not be important at
all (I never had a problem with pkg-config not being installed, even on Mac OS), but
it's still nice.
I have no idea how well this interacts with using special environment variables to specify a custom location for SDL, or how it should interact at all. It may be necessary to expand the find script for this if this turns out to be an issue.
> Use custom find_module for SDL2_image instead of PkgConfig.

- CMakeLists.txt
The header files do not need to be compiled, so it may not seem like they need to be in CMakeLists.txt, but that is wrong. Changes to them still trigger recompiles elsewhere, so CMake needs to be aware of them to include them in the generated dependency tracking. Also, without this, the headers aren't in the generated IDE files, which makes life surprisingly annoying.
This is completely independent of #348, and I expect no issues with merging this.
> Add the headers of our files to CMakeLists

- src/core/system.c
The previous code attempted to add a newline at the start, which then got immediately overwritten by the
following code. The new code adds a newline at the end, which actually works. This was just a minor thing that annoyed me.
(cherry picked from commit c95f7fd49efb500f849815be24eccf37e08e89b2)
> Add proper newlines to debug log.

- src/engine.cpp
a logging attempt donw but it leads to segfaulting
since some allocations done in Engine_Init_Pre
are needed for it, thus swapping their places here.
> If the config.lua file is not found then there is

- README.md
- Make the readme easier to read.
- Make the readme easier to navigate.
- Allow linking to specific sections of the readme.
- Fix bug in readme markdown that caused the "What is this?" heading to be shown as item 10 of the TOC.
> Linkify README.md table of contents

- src/game.cpp
A very easy, self explanatory fix for #378. 
I did a quick search and `ent->character->cmd.rot[1]`seems to be used only for movement underwater, so I can't foresee any issues caused by this change elsewhere.
> Fix inverted swimming gamepad controls while underwater (#378)

- README.md
Looks like splitting the Build status line breaks the link. Not sure why I didn't pick this up before, sorry. 
This breaks the 80 char line limit, but I don't see any other way around it.
> Fix Build Status in README.md

- src/fmv/internal/common.h
MSVC does not provide __builtin_clz intrinsic, but hopefully a portable implementation is available in the "#if 0" and it could be used in these circumstances,
> Fix compilation on MSVC

- CMakeLists.txt
- src/core/gl_font.c
These are some of the fixes that I made to OpenTomb when I tried to compile it on MSVC.
See also issue #504.
- I added an option to CMakeList.txt for selecting between system provided FreeType and the other one. By default, if no options are specified, it uses the one included in the main sources, like now. When cmake is called with "-DFORCE_SYSTEM_FREETYPE=on", then it tries to search for a local copy. If it is not found, or if the option is not specified, the interal copy will be used.
- Fixed conflicts of include files between the system provided FreeType and the internal copy.
- Hide warning C4996, which is emitted when an "unsafe" function is used on MSVC.
I tried to do the first fix also for Bullet and LUA, but I have not a system provided copy of Bullet even on CYGWIN (so I could …
> Build fixes

- src/fmv/stream_codec.c
- src/fmv/stream_codec.h
With reference to issue #504, pthread_t is an opaque object and it is better to not handle it like an 'int' type. Actually, it rises an error with the pthread implementation in VS 2017. Attached patch fixes this thing.
> pthread_t should not be used as 'int' type

- src/fmv/codecs/adpcm.c
- src/fmv/codecs/adpcm_data.c
- src/fmv/codecs/adpcm_data.h
This patch closes issue #534.
Sincerely.
> Type mismatch during full C++ build (Windows, MSVC).

- CMakeLists.txt
Hi,
Using system-provided FreeType library is not working on Linux due to case sensitivity :
```
ar@ar-i7:~/Documents/OpenTomb/build$ cmake -DFORCE_SYSTEM_FREETYPE=ON ..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:17 …
```
> Made CMake selection of FreeType library work on Linux.

- ENGINE.md
> ENGINE.md: Fixed typos
